// Autogenerated from Pigeon (v12.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';
List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

enum PigeonScanSource {
  wifi,
  bluetooth,
}

class DeviceDto {
  DeviceDto({
    required this.id,
    required this.name,
    this.manufacturer,
    required this.source,
    this.ipAddress,
    this.rssi,
    this.isTrusted,
    this.riskLevel,
  });

  String id;

  String name;

  String? manufacturer;

  PigeonScanSource source;

  String? ipAddress;

  int? rssi;

  bool? isTrusted;

  String? riskLevel;

  Object encode() {
    return <Object?>[
      id,
      name,
      manufacturer,
      source.index,
      ipAddress,
      rssi,
      isTrusted,
      riskLevel,
    ];
  }

  static DeviceDto decode(Object result) {
    result as List<Object?>;
    return DeviceDto(
      id: result[0]! as String,
      name: result[1]! as String,
      manufacturer: result[2] as String?,
      source: PigeonScanSource.values[result[3]! as int],
      ipAddress: result[4] as String?,
      rssi: result[5] as int?,
      isTrusted: result[6] as bool?,
      riskLevel: result[7] as String?,
    );
  }
}

class ScanResultDto {
  ScanResultDto({
    required this.source,
    required this.devices,
  });

  PigeonScanSource source;

  List<DeviceDto?> devices;

  Object encode() {
    return <Object?>[
      source.index,
      devices,
    ];
  }

  static ScanResultDto decode(Object result) {
    result as List<Object?>;
    return ScanResultDto(
      source: PigeonScanSource.values[result[0]! as int],
      devices: (result[1] as List<Object?>?)!.cast<DeviceDto?>(),
    );
  }
}

class _ScannerHostApiCodec extends StandardMessageCodec {
  const _ScannerHostApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is DeviceDto) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return DeviceDto.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class ScannerHostApi {
  /// Constructor for [ScannerHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ScannerHostApi({BinaryMessenger? binaryMessenger})
      : _binaryMessenger = binaryMessenger;
  final BinaryMessenger? _binaryMessenger;

  static const MessageCodec<Object?> codec = _ScannerHostApiCodec();

  Future<List<DeviceDto?>> getNetworkDevices() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.hidden_camera_detector.ScannerHostApi.getNetworkDevices', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(null) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as List<Object?>?)!.cast<DeviceDto?>();
    }
  }

  Future<List<DeviceDto?>> getBluetoothDevices() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.hidden_camera_detector.ScannerHostApi.getBluetoothDevices', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(null) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as List<Object?>?)!.cast<DeviceDto?>();
    }
  }

  Future<void> startScan(PigeonScanSource arg_source) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.hidden_camera_detector.ScannerHostApi.startScan', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_source.index]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> stopScan(PigeonScanSource arg_source) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.hidden_camera_detector.ScannerHostApi.stopScan', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_source.index]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }
}

class _ScannerFlutterApiCodec extends StandardMessageCodec {
  const _ScannerFlutterApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is DeviceDto) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is ScanResultDto) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return DeviceDto.decode(readValue(buffer)!);
      case 129: 
        return ScanResultDto.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

abstract class ScannerFlutterApi {
  static const MessageCodec<Object?> codec = _ScannerFlutterApiCodec();

  void onScanResult(ScanResultDto result);

  static void setup(ScannerFlutterApi? api, {BinaryMessenger? binaryMessenger}) {
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.hidden_camera_detector.ScannerFlutterApi.onScanResult', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.hidden_camera_detector.ScannerFlutterApi.onScanResult was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final ScanResultDto? arg_result = (args[0] as ScanResultDto?);
          assert(arg_result != null,
              'Argument for dev.flutter.pigeon.hidden_camera_detector.ScannerFlutterApi.onScanResult was null, expected non-null ScanResultDto.');
          try {
            api.onScanResult(arg_result!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
