// Autogenerated from Pigeon (v26.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSUInteger, HCDScanSourceDto) {
  HCDScanSourceDtoWifi = 0,
  HCDScanSourceDtoBluetooth = 1,
};

/// Wrapper for HCDScanSourceDto to allow for nullability.
@interface HCDScanSourceDtoBox : NSObject
@property(nonatomic, assign) HCDScanSourceDto value;
- (instancetype)initWithValue:(HCDScanSourceDto)value;
@end

typedef NS_ENUM(NSUInteger, HCDDeviceRiskLevelDto) {
  HCDDeviceRiskLevelDtoLow = 0,
  HCDDeviceRiskLevelDtoMedium = 1,
  HCDDeviceRiskLevelDtoHigh = 2,
  HCDDeviceRiskLevelDtoUnknown = 3,
};

/// Wrapper for HCDDeviceRiskLevelDto to allow for nullability.
@interface HCDDeviceRiskLevelDtoBox : NSObject
@property(nonatomic, assign) HCDDeviceRiskLevelDto value;
- (instancetype)initWithValue:(HCDDeviceRiskLevelDto)value;
@end

typedef NS_ENUM(NSUInteger, HCDPermissionStatusDto) {
  HCDPermissionStatusDtoGranted = 0,
  HCDPermissionStatusDtoDenied = 1,
  HCDPermissionStatusDtoPermanentlyDenied = 2,
};

/// Wrapper for HCDPermissionStatusDto to allow for nullability.
@interface HCDPermissionStatusDtoBox : NSObject
@property(nonatomic, assign) HCDPermissionStatusDto value;
- (instancetype)initWithValue:(HCDPermissionStatusDto)value;
@end

@class HCD_PigeonConfig;
@class HCDDeviceDto;
@class HCDDeviceEventDto;

@interface HCD_PigeonConfig : NSObject
@end

/// Mirrors the Flutter `DetectedDevice` entity. Field documentation ensures a
/// predictable conversion between native JSON/dictionary payloads and the Dart
/// domain model:
/// - `id`: MAC address or UUID string.
/// - `name`: Human-readable device name (default to "Unknown Device").
/// - `source`: Originating scan type; used to route updates in Dart.
/// - `manufacturer`: Optional manufacturer string.
/// - `ipAddress`: Optional IPv4/IPv6 string for Wi-Fi devices.
/// - `rssi`: Received signal strength in dBm (Bluetooth only).
/// - `isTrusted`: Whether the device is user-whitelisted.
/// - `riskLevel`: Maps to `DeviceRiskLevel` enum.
@interface HCDDeviceDto : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithId:(NSString *)id
    name:(NSString *)name
    source:(HCDScanSourceDto)source
    manufacturer:(nullable NSString *)manufacturer
    ipAddress:(nullable NSString *)ipAddress
    rssi:(nullable NSNumber *)rssi
    isTrusted:(BOOL )isTrusted
    riskLevel:(nullable HCDDeviceRiskLevelDtoBox *)riskLevel;
@property(nonatomic, copy) NSString * id;
@property(nonatomic, copy) NSString * name;
@property(nonatomic, assign) HCDScanSourceDto source;
@property(nonatomic, copy, nullable) NSString * manufacturer;
@property(nonatomic, copy, nullable) NSString * ipAddress;
@property(nonatomic, strong, nullable) NSNumber * rssi;
@property(nonatomic, assign) BOOL  isTrusted;
@property(nonatomic, strong, nullable) HCDDeviceRiskLevelDtoBox * riskLevel;
@end

/// Streaming payload delivered from native scanners. Every event represents a
/// single discovery update so the Dart layer can surface incremental results.
/// `eventId` is a monotonically increasing identifier per scan to help debounce
/// duplicates; `totalDiscovered` tracks the best-effort count emitted so far.
@interface HCDDeviceEventDto : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithSource:(HCDScanSourceDto)source
    device:(HCDDeviceDto *)device
    eventId:(NSInteger )eventId
    totalDiscovered:(nullable NSNumber *)totalDiscovered
    isFinal:(BOOL )isFinal;
@property(nonatomic, assign) HCDScanSourceDto source;
@property(nonatomic, strong) HCDDeviceDto * device;
@property(nonatomic, assign) NSInteger  eventId;
@property(nonatomic, strong, nullable) NSNumber * totalDiscovered;
@property(nonatomic, assign) BOOL  isFinal;
@end

/// The codec used by all APIs.
NSObject<FlutterMessageCodec> *HCDGetScannerApiCodec(void);

@protocol HCDScannerHostApi
- (void)requestLocalNetworkAuthorizationWithCompletion:(void (^)(HCDPermissionStatusDtoBox *_Nullable, FlutterError *_Nullable))completion;
- (void)startWifiScanWithCompletion:(void (^)(FlutterError *_Nullable))completion;
- (void)stopWifiScanWithCompletion:(void (^)(FlutterError *_Nullable))completion;
- (void)startBluetoothScanWithCompletion:(void (^)(FlutterError *_Nullable))completion;
- (void)stopBluetoothScanWithCompletion:(void (^)(FlutterError *_Nullable))completion;
@end

extern void SetUpHCDScannerHostApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<HCDScannerHostApi> *_Nullable api);

extern void SetUpHCDScannerHostApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<HCDScannerHostApi> *_Nullable api, NSString *messageChannelSuffix);


@interface HCDScannerStreamApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger messageChannelSuffix:(nullable NSString *)messageChannelSuffix;
- (void)onDeviceEventEvent:(HCDDeviceEventDto *)event completion:(void (^)(FlutterError *_Nullable))completion;
@end

NS_ASSUME_NONNULL_END
