// Autogenerated from Pigeon (v12.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSUInteger, HCDPigeonScanSource) {
  HCDPigeonScanSourceWifi = 0,
  HCDPigeonScanSourceBluetooth = 1,
};

/// Wrapper for HCDPigeonScanSource to allow for nullability.
@interface HCDPigeonScanSourceBox : NSObject
@property(nonatomic, assign) HCDPigeonScanSource value;
- (instancetype)initWithValue:(HCDPigeonScanSource)value;
@end

@class HCDDeviceDto;
@class HCDScanResultDto;

@interface HCDDeviceDto : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithId:(NSString *)id
    name:(NSString *)name
    manufacturer:(nullable NSString *)manufacturer
    source:(HCDPigeonScanSource)source
    ipAddress:(nullable NSString *)ipAddress
    rssi:(nullable NSNumber *)rssi
    isTrusted:(nullable NSNumber *)isTrusted
    riskLevel:(nullable NSString *)riskLevel;
@property(nonatomic, copy) NSString * id;
@property(nonatomic, copy) NSString * name;
@property(nonatomic, copy, nullable) NSString * manufacturer;
@property(nonatomic, assign) HCDPigeonScanSource source;
@property(nonatomic, copy, nullable) NSString * ipAddress;
@property(nonatomic, strong, nullable) NSNumber * rssi;
@property(nonatomic, strong, nullable) NSNumber * isTrusted;
@property(nonatomic, copy, nullable) NSString * riskLevel;
@end

@interface HCDScanResultDto : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithSource:(HCDPigeonScanSource)source
    devices:(NSArray<HCDDeviceDto *> *)devices;
@property(nonatomic, assign) HCDPigeonScanSource source;
@property(nonatomic, strong) NSArray<HCDDeviceDto *> * devices;
@end

/// The codec used by HCDScannerHostApi.
NSObject<FlutterMessageCodec> *HCDScannerHostApiGetCodec(void);

@protocol HCDScannerHostApi
- (void)getNetworkDevicesWithCompletion:(void (^)(NSArray<HCDDeviceDto *> *_Nullable, FlutterError *_Nullable))completion;
- (void)getBluetoothDevicesWithCompletion:(void (^)(NSArray<HCDDeviceDto *> *_Nullable, FlutterError *_Nullable))completion;
- (void)startScanSource:(HCDPigeonScanSource)source completion:(void (^)(FlutterError *_Nullable))completion;
- (void)stopScanSource:(HCDPigeonScanSource)source completion:(void (^)(FlutterError *_Nullable))completion;
@end

extern void SetUpHCDScannerHostApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<HCDScannerHostApi> *_Nullable api);

/// The codec used by HCDScannerFlutterApi.
NSObject<FlutterMessageCodec> *HCDScannerFlutterApiGetCodec(void);

@interface HCDScannerFlutterApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)onScanResultResult:(HCDScanResultDto *)result completion:(void (^)(FlutterError *_Nullable))completion;
@end

NS_ASSUME_NONNULL_END
