// Autogenerated from Pigeon (v12.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "ScannerApi.g.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

@implementation HCDPigeonScanSourceBox
- (instancetype)initWithValue:(HCDPigeonScanSource)value {
  self = [super init];
  if (self) {
    _value = value;
  }
  return self;
}
@end

static NSArray *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}
static id GetNullableObjectAtIndex(NSArray *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@interface HCDDeviceDto ()
+ (HCDDeviceDto *)fromList:(NSArray *)list;
+ (nullable HCDDeviceDto *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface HCDScanResultDto ()
+ (HCDScanResultDto *)fromList:(NSArray *)list;
+ (nullable HCDScanResultDto *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@implementation HCDDeviceDto
+ (instancetype)makeWithId:(NSString *)id
    name:(NSString *)name
    manufacturer:(nullable NSString *)manufacturer
    source:(HCDPigeonScanSource)source
    ipAddress:(nullable NSString *)ipAddress
    rssi:(nullable NSNumber *)rssi
    isTrusted:(nullable NSNumber *)isTrusted
    riskLevel:(nullable NSString *)riskLevel {
  HCDDeviceDto* pigeonResult = [[HCDDeviceDto alloc] init];
  pigeonResult.id = id;
  pigeonResult.name = name;
  pigeonResult.manufacturer = manufacturer;
  pigeonResult.source = source;
  pigeonResult.ipAddress = ipAddress;
  pigeonResult.rssi = rssi;
  pigeonResult.isTrusted = isTrusted;
  pigeonResult.riskLevel = riskLevel;
  return pigeonResult;
}
+ (HCDDeviceDto *)fromList:(NSArray *)list {
  HCDDeviceDto *pigeonResult = [[HCDDeviceDto alloc] init];
  pigeonResult.id = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.id != nil, @"");
  pigeonResult.name = GetNullableObjectAtIndex(list, 1);
  NSAssert(pigeonResult.name != nil, @"");
  pigeonResult.manufacturer = GetNullableObjectAtIndex(list, 2);
  pigeonResult.source = [GetNullableObjectAtIndex(list, 3) integerValue];
  pigeonResult.ipAddress = GetNullableObjectAtIndex(list, 4);
  pigeonResult.rssi = GetNullableObjectAtIndex(list, 5);
  pigeonResult.isTrusted = GetNullableObjectAtIndex(list, 6);
  pigeonResult.riskLevel = GetNullableObjectAtIndex(list, 7);
  return pigeonResult;
}
+ (nullable HCDDeviceDto *)nullableFromList:(NSArray *)list {
  return (list) ? [HCDDeviceDto fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.id ?: [NSNull null]),
    (self.name ?: [NSNull null]),
    (self.manufacturer ?: [NSNull null]),
    @(self.source),
    (self.ipAddress ?: [NSNull null]),
    (self.rssi ?: [NSNull null]),
    (self.isTrusted ?: [NSNull null]),
    (self.riskLevel ?: [NSNull null]),
  ];
}
@end

@implementation HCDScanResultDto
+ (instancetype)makeWithSource:(HCDPigeonScanSource)source
    devices:(NSArray<HCDDeviceDto *> *)devices {
  HCDScanResultDto* pigeonResult = [[HCDScanResultDto alloc] init];
  pigeonResult.source = source;
  pigeonResult.devices = devices;
  return pigeonResult;
}
+ (HCDScanResultDto *)fromList:(NSArray *)list {
  HCDScanResultDto *pigeonResult = [[HCDScanResultDto alloc] init];
  pigeonResult.source = [GetNullableObjectAtIndex(list, 0) integerValue];
  pigeonResult.devices = GetNullableObjectAtIndex(list, 1);
  NSAssert(pigeonResult.devices != nil, @"");
  return pigeonResult;
}
+ (nullable HCDScanResultDto *)nullableFromList:(NSArray *)list {
  return (list) ? [HCDScanResultDto fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    @(self.source),
    (self.devices ?: [NSNull null]),
  ];
}
@end

@interface HCDScannerHostApiCodecReader : FlutterStandardReader
@end
@implementation HCDScannerHostApiCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 128: 
      return [HCDDeviceDto fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface HCDScannerHostApiCodecWriter : FlutterStandardWriter
@end
@implementation HCDScannerHostApiCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[HCDDeviceDto class]]) {
    [self writeByte:128];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface HCDScannerHostApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation HCDScannerHostApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[HCDScannerHostApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[HCDScannerHostApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *HCDScannerHostApiGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    HCDScannerHostApiCodecReaderWriter *readerWriter = [[HCDScannerHostApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}

void SetUpHCDScannerHostApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<HCDScannerHostApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.hidden_camera_detector.ScannerHostApi.getNetworkDevices"
        binaryMessenger:binaryMessenger
        codec:HCDScannerHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getNetworkDevicesWithCompletion:)], @"HCDScannerHostApi api (%@) doesn't respond to @selector(getNetworkDevicesWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api getNetworkDevicesWithCompletion:^(NSArray<HCDDeviceDto *> *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.hidden_camera_detector.ScannerHostApi.getBluetoothDevices"
        binaryMessenger:binaryMessenger
        codec:HCDScannerHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getBluetoothDevicesWithCompletion:)], @"HCDScannerHostApi api (%@) doesn't respond to @selector(getBluetoothDevicesWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api getBluetoothDevicesWithCompletion:^(NSArray<HCDDeviceDto *> *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.hidden_camera_detector.ScannerHostApi.startScan"
        binaryMessenger:binaryMessenger
        codec:HCDScannerHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(startScanSource:completion:)], @"HCDScannerHostApi api (%@) doesn't respond to @selector(startScanSource:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        HCDPigeonScanSource arg_source = [GetNullableObjectAtIndex(args, 0) integerValue];
        [api startScanSource:arg_source completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.hidden_camera_detector.ScannerHostApi.stopScan"
        binaryMessenger:binaryMessenger
        codec:HCDScannerHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(stopScanSource:completion:)], @"HCDScannerHostApi api (%@) doesn't respond to @selector(stopScanSource:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        HCDPigeonScanSource arg_source = [GetNullableObjectAtIndex(args, 0) integerValue];
        [api stopScanSource:arg_source completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
@interface HCDScannerFlutterApiCodecReader : FlutterStandardReader
@end
@implementation HCDScannerFlutterApiCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 128: 
      return [HCDDeviceDto fromList:[self readValue]];
    case 129: 
      return [HCDScanResultDto fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface HCDScannerFlutterApiCodecWriter : FlutterStandardWriter
@end
@implementation HCDScannerFlutterApiCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[HCDDeviceDto class]]) {
    [self writeByte:128];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[HCDScanResultDto class]]) {
    [self writeByte:129];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface HCDScannerFlutterApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation HCDScannerFlutterApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[HCDScannerFlutterApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[HCDScannerFlutterApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *HCDScannerFlutterApiGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    HCDScannerFlutterApiCodecReaderWriter *readerWriter = [[HCDScannerFlutterApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}

@interface HCDScannerFlutterApi ()
@property(nonatomic, strong) NSObject<FlutterBinaryMessenger> *binaryMessenger;
@end

@implementation HCDScannerFlutterApi

- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger {
  self = [super init];
  if (self) {
    _binaryMessenger = binaryMessenger;
  }
  return self;
}
- (void)onScanResultResult:(HCDScanResultDto *)arg_result completion:(void (^)(FlutterError *_Nullable))completion {
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:@"dev.flutter.pigeon.hidden_camera_detector.ScannerFlutterApi.onScanResult"
      binaryMessenger:self.binaryMessenger
      codec:HCDScannerFlutterApiGetCodec()];
  [channel sendMessage:@[arg_result ?: [NSNull null]] reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion([FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        completion(nil);
      }
    } else {
      completion([FlutterError errorWithCode:@"channel-error" message:@"Unable to establish connection on channel." details:@""]);
    } 
  }];
}
@end

